### ISSUE TITLE
Advanced Miner

### ISSUE THREAD

**Issue by Lt-Sparky** [kremnev8/DSP-Mods#37]
![advancedminer](https://user-images.githubusercontent.com/85095233/151687945-e6bfb8ad-039f-4b39-b750-99e5f58fd30b.jpg)

**Comment by Lt-Sparky** [comment]
Just when you have time...

**Comment by kremnev8** [comment]
Unfortunately I have to inform you that since devs have released update with miner mk.2, this mod is deprecated and will not get any updates. You have to uninstall this mod to continue playing. Also note that if you save your games with the mod active, later removing the mod is going to auto delete all missing machines. (Make sure to update CommonAPI)
