### ISSUE TITLE
[BUG] - Cant deliver goods via belts to gigastations

### ISSUE THREAD

**Issue by BlutVampir** [kremnev8/DSP-Mods#79]
**Describe the bug**
Can attach belts to the gigastation, with the goods I declare. to goods l are on the belt, but are note added to the gigastation. gigastation keeps empty.

**To Reproduce**
Build gigastation, attach a belt. Define an item in gigastation. Deliver the goods via belt. nothing happens

**Expected behavior**
Inventory should get higher.

**Comment by kremnev8** [comment]
Hm. I'm unable to replicate your issue:
![изображение](https://github.com/kremnev8/DSP-Mods/assets/12484618/c595c1b9-e22a-4bb4-8515-92317884e766)
![изображение](https://github.com/kremnev8/DSP-Mods/assets/12484618/d252ac8d-7fa6-4bb8-9f8d-97a04e17427a)

**Comment by PiggyWhiskey** [comment]
This occurs for me in very some situations.
Slots 1-6 need to be fulfilled (At or above Max)
Belts will then fail to input anything

This is presumably vanilla hard-coded to check 6 slots (5 vanilla ILS + Warper) and once these have been fulfilled, it disables belts trying to find space to save UPS.

I've only noticed this behaviour since the Dark Fog.
And slots 7-12 doesn't seem to bother Drones/Vessel movements.

The workaround is to only use slots 1-6 for belted items while all slots are valid for Drone/Vessel

**Comment by kremnev8** [comment]
Interesting. I will investigate.

**Comment by kremnev8** [comment]
Issue has been fixed in v2.3.5
